# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: dgoldfarb.github@gmail.com
author_name: Daniel Goldfarb
has_binder: false
has_settings: false
kind: frontend
labextension_name: pydjlx
project_short_description: A JupyterLab extension demo for PyData Tel Aviv
python_name: pydjlx
repository: https://github.com/DanielGoldfarb/pydjlx
test: false

